### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by alekseykulikov**

### CODE REVIEW

**Comment by alekseykulikov** [comment]
I also think, that it would be nice to optionally pass `debug` directly as a first argument.
In this case you don't need to repeat namespace string and also can customise `debug.log` method.
What do you think? Code change is:

``` js
var debug = typeof namespace == 'function' ? namespace : Debug(namespace);
```

**Comment by Twipped** [comment]
That sounds like a good idea. Go ahead and add it to this PR and I'll merge it.

**Comment by alekseykulikov** [comment]
Good, now it's ready for next release :)

**Comment by Twipped** [comment]
1.0.0 release is now published.

**Pull request merged**
